language: python
python:
  - 3.6
  - 3.7
dist: xenial
sudo: true
install:
  - pip install -r requirements.dev.txt
script:
  - nosetests --with-coverage --cover-package=shrug_lang
after_success:
  - coveralls
